### PR TITLE
portsnap: New completion.

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Hi,
I create a bash completion for FreeBSD ports collection update tool - Portsnap, hoping this can help someone else, so I send this pull request, if I need to modify or improve somewhere, please just tell me, thanks!
Best regards!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
create auto completion for freebsd-update :D

**Comment by PeterDaveHello** [comment]
Hi, @GArik 
Are you there@@?

**Comment by GArik** [comment]
Hi :)
Sorry for the delay. I'll review your pull request tonight.

**Comment by GArik** [comment]
Your completions are good, but some minor corrections should be made before they can be merged:
-  Long lines should be wrapped. 79 characters is a maximum line width.
-  `freebsd-update` and `portsnap` should be listed in `bashcomp_DATA` variable in `completions/Makefile.am`.
-  All options that have arguments should be handled in the `case $prev in` construct. If it is hard to complete argument for some options, you can add the stub completion for them like this:

```
        -k|-r|-s|-t)
            # argument required but no completions available
            return
```
-  It would be nice to provide the file path completion after the `portsnap extract` command.

Thanks for your contribution :)

**Comment by PeterDaveHello** [comment]
okay, I will fix it.

**Comment by PeterDaveHello** [comment]
Hi @GArik,
Thanks for your help, I fix it, and I contacted to the project manager to join this project, but I got some problem while registering my alioth account, so please cherry-pick my commits to project's master branch for me, I will try to send commits by my self ASAP, thanks a lot!
Best regards,
Peter.

**Comment by GArik** [comment]
In. I had to modify your commits a bit, you can review them here:
https://alioth.debian.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=bash-completion/bash-completion.git;a=commit;h=5ff5a4e0f875e8d1a49848408cfe72778889cbe8
https://alioth.debian.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=bash-completion/bash-completion.git;a=commit;h=c3770c17984bb61255db6adb48886b466c335e03

Thanks.

**Comment by PeterDaveHello** [comment]
Thanks @GArik, maybe you can tell me to modify by my self next time :)

**Comment by GArik** [comment]
I did that. See comment #4 :)

**Pull request closed without merging**
